services:
  db:
    image: mysql:5.7
    container_name: lain-ctf-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass_lain
      MYSQL_DATABASE: lain
      MYSQL_USER: lain
      MYSQL_PASSWORD: lainpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - lain-db-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-prootpass_lain",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - lain-net

  web:
    build: .
    container_name: lain-ctf-web
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      DB_HOST: db
      DB_NAME: lain
      DB_USER: lain
      DB_PASS: lainpass
      FLAG_SQLI: "LainCTF{bl1nd_but_n0t_br0k3n}"
      FLAG_ADMIN: "LainCTF{w3lc0m3_t0_th3_w1r3d}"
      FLAG_DECOY: "LainCTF{d3c0y_tr4p_th1s_1s_n0t_th3_fl4g}"
      ADMIN_USERNAME: "lain_chrono"
      ADMIN_PASSWORD: "Tr1gger_Sh1nji_1998"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lain-net

volumes:
  lain-db-data:

networks:
  lain-net:
    driver: bridge
